# Orb 'circleci/python@0.2.1' resolved to 'circleci/python@0.2.1'
version: 2
jobs:
  build-and-test:
    docker:
    - image: rfhk/odoo:12.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
            pip install -r requirements.txt
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: ls /odoo
        name: Odoo Directory
workflows:
  main:
    jobs:
    - build-and-test
  version: 2
